# Configuration
variables:
  OUTPUTDIR: /tmp/docs-html/

# Docker image
image: "python:latest"

# Dependencies
before_script:
  # SSH deploy key
  - 'which ssh-agent || apt-get -y install openssh-client'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

# Github mirror
mirror Github:
  script:
  - cd $CI_PROJECT_DIR
  - git checkout --track origin/$CI_BUILD_REF_NAME
  - git remote add github git@github.com:snowflakeOps/documentation.git
  - git push github $CI_BUILD_REF_NAME

# Deploy
deploy STAGE:
  type: deploy
  environment: STAGE
  script:
  - apt-get -y update && apt-get -y install rsync
  - pip install Sphinx
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-versioning
  - cd $CI_PROJECT_DIR
  - sphinx-versioning build . $OUTPUTDIR -b -B 201501 -r 201501
  - rsync -avz --delete $OUTPUTDIR docsstage@hosting04.snowflakehosting.ch:~/www/

deploy PROD:
  type: deploy
  when: manual
  environment: PROD
  script:
  - apt-get -y update && apt-get -y install rsync
  - pip install Sphinx
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-versioning
  - cd $CI_PROJECT_DIR
  - sphinx-versioning build . $OUTPUTDIR -b -B 201501 -r 201501
  - rsync -avz --delete $OUTPUTDIR docsprod@hosting04.snowflakehosting.ch:~/www/

