# Configuration
variables:
  OUTPUTDIR: /tmp/docs-html/

# Docker image
image: "python:latest"

# Define stages
stages:
- mirror
- deploy stage
- deploy prod

# Dependencies
before_script:
  # SSH deploy key
  - 'which ssh-agent || apt-get -y install openssh-client'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

# Github mirror
mirror Github:
 stage: mirror
  allow_failure: true
  only:
  - saas
  script:
  - cd $CI_PROJECT_DIR
  - git checkout --track origin/$CI_BUILD_REF_NAME
  - git remote add github git@github.com:opsone-ch/documentation.git
  - git push github $CI_BUILD_REF_NAME

# Deploy
deploy STAGE:
  stage: deploy stage
  type: deploy
  environment: STAGE
  script:
  - apt-get -y update && apt-get -y install rsync
# Remove version as soon as https://github.com/Robpol86/sphinxcontrib-versioning/issues/39 is fixed
  - pip install Sphinx==1.5.6
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-versioning
  - cd $CI_PROJECT_DIR
  - sphinx-versioning build . $OUTPUTDIR --root-ref saas
  - rsync -avz --delete $OUTPUTDIR $STAGE_USERNAME@$STAGE_SERVERNAME:~/www/

deploy PROD:
  stage: deploy prod
  type: deploy
  when: manual
  environment: PROD
  script:
  - apt-get -y update && apt-get -y install rsync
# Remove version as soon as https://github.com/Robpol86/sphinxcontrib-versioning/issues/39 is fixed
  - pip install Sphinx==1.5.6
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-versioning
  - cd $CI_PROJECT_DIR
  - sphinx-versioning build . $OUTPUTDIR --root-ref saas
  - rsync -avz --delete $OUTPUTDIR $PROD_USERNAME@$PROD_SERVERNAME:~/www/

