# Build
build:
  stage: build
  artifacts:
    paths:
    - $OUTPUTDIR
    expire_in: 1 week
  script:
  # Remove version as soon as https://github.com/Robpol86/sphinxcontrib-versioning/issues/39 is fixed
  - pip install Sphinx==1.5.6
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-versioning
  - cd $CI_PROJECT_DIR
  - sphinx-versioning build . $OUTPUTDIR --root-ref $VERSION
